server {
    listen 80;
    server_name _;
    resolver 127.0.0.11 ipv6=off valid=10s;

    location = / {
        return 404;
    }

    location /auth/v1/ {
        set $auth_upstream auth:8081;
        rewrite ^/auth/v1/(.*)$ /$1 break;
        proxy_pass http://$auth_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /rest/v1/ {
        set $rest_upstream rest:3000;
        rewrite ^/rest/v1/(.*)$ /$1 break;
        proxy_pass http://$rest_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
